<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="1" failed="1" ignored="0" total="3" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="11082" started-at="2022-11-26T09:16:34 IST" finished-at="2022-11-26T09:16:46 IST">
    <groups>
    </groups>
    <test name="Default test" duration-ms="11082" started-at="2022-11-26T09:16:34 IST" finished-at="2022-11-26T09:16:46 IST">
      <class name="core.ExtentReport">
        <test-method status="PASS" signature="beforeTest()[pri:0, instance:core.ExtentReport@1d8db5a]" name="beforeTest" is-config="true" duration-ms="132" started-at="2022-11-26T09:16:34 IST" finished-at="2022-11-26T09:16:35 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeTest -->
        <test-method status="PASS" signature="test_case_1()[pri:0, instance:core.ExtentReport@1d8db5a]" name="test_case_1" duration-ms="10301" started-at="2022-11-26T09:16:35 IST" finished-at="2022-11-26T09:16:45 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test_case_1 -->
        <test-method status="PASS" signature="getResult(org.testng.ITestResult)[pri:0, instance:core.ExtentReport@1d8db5a]" name="getResult" is-config="true" duration-ms="3" started-at="2022-11-26T09:16:45 IST" finished-at="2022-11-26T09:16:45 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=test_case_1 status=SUCCESS method=ExtentReport.test_case_1()[pri:0, instance:core.ExtentReport@1d8db5a] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getResult -->
        <test-method status="FAIL" signature="test_case_2()[pri:0, instance:core.ExtentReport@1d8db5a]" name="test_case_2" duration-ms="3" started-at="2022-11-26T09:16:45 IST" finished-at="2022-11-26T09:16:45 IST">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at org.testng.Assert.assertTrue(Assert.java:55)
at core.ExtentReport.test_case_2(ExtentReport.java:61)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1259)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test_case_2 -->
        <test-method status="PASS" signature="getResult(org.testng.ITestResult)[pri:0, instance:core.ExtentReport@1d8db5a]" name="getResult" is-config="true" duration-ms="4" started-at="2022-11-26T09:16:45 IST" finished-at="2022-11-26T09:16:45 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=test_case_2 status=FAILURE method=ExtentReport.test_case_2()[pri:0, instance:core.ExtentReport@1d8db5a] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getResult -->
        <test-method status="SKIP" signature="test_case_3()[pri:0, instance:core.ExtentReport@1d8db5a]" name="test_case_3" duration-ms="2" started-at="2022-11-26T09:16:45 IST" finished-at="2022-11-26T09:16:45 IST">
          <exception class="org.testng.SkipException">
            <message>
              <![CDATA[This test Case has been skipped]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.SkipException: This test Case has been skipped
at core.ExtentReport.test_case_3(ExtentReport.java:69)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1259)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.SkipException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test_case_3 -->
        <test-method status="PASS" signature="getResult(org.testng.ITestResult)[pri:0, instance:core.ExtentReport@1d8db5a]" name="getResult" is-config="true" duration-ms="1" started-at="2022-11-26T09:16:45 IST" finished-at="2022-11-26T09:16:45 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=test_case_3 status=SKIP method=ExtentReport.test_case_3()[pri:0, instance:core.ExtentReport@1d8db5a] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getResult -->
        <test-method status="PASS" signature="afterTest()[pri:0, instance:core.ExtentReport@1d8db5a]" name="afterTest" is-config="true" duration-ms="580" started-at="2022-11-26T09:16:45 IST" finished-at="2022-11-26T09:16:46 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterTest -->
      </class> <!-- core.ExtentReport -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
